### ISSUE TITLE
variety of errors on 1.18.x releases off curseforge

### ISSUE THREAD

**Issue by averycoolbean** [Verph/TFC-Florae#5]
upon launching the game with tfc florae 

```TFC Florae (tfcflorae) encountered an error during the common_setup event phase
java.lang.NoSuchMethodError: 'void
net.dries007.tfc.common.blocks.wood.TFCLeavesBlock.<init>(net.dries007.tfc.common.blocks.ExtendedProperties, int)'

TFC Florae (tfcflorae) encountered an error during the error event phase
java.lang.NullPointerException: Registry Object not present:
tfcflorae:wood/leaves/argyle_eucalyptus

TFC Florae (tfcflorae) encountered an error during the error event phase
java.lang.NullPointerException: Regsitry Object not present:
tfcflorae:wood/sapling/blue_bamboo

TFC Florae (tfcflorae) encountered an error during the error event phase
java.lang.ExceptionInInitializerError: null
```

with the following crash report:
[crash-2023-05-03_02.09.08-fml.txt](https://github.com/Verph/TFC-Florae/files/11378479/crash-2023-05-03_02.09.08-fml.txt)

im assuming it is an issue on this end as the extra steps and dependencies are clarified to only be relevant to 1.12.2 but please correct me if there are some extra steps i have indeed missed

**Comment by Verph** [comment]
Florae v2.0.5 is not compatible with TFC v2.2.17 or later, since they changed how leaves work. This is fixed in dev.

**Comment by averycoolbean** [comment]
gotcha, thank you
